# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - roommaster-backend

on:
  push:
    branches:
      - deploymenttest
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build application
        run: yarn build

      - name: Re-install only production dependencies
        run: |
          rm -rf node_modules
          yarn install --production --frozen-lockfile --ignore-scripts --prefer-offline

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Install Zip
        run: sudo apt-get install -y zip

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git*" "src/*" "tests/*" "scripts/*" "docs/*" ".github/*" "docker-compose*" "terraform/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Verify artifact
        run: ls -la release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'roommaster-backend'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3CAC2105623F4A1A87D66297DC110945 }}
          # Ensure you set the Startup Command in Azure Portal -> Configuration -> General Settings:
          # npx prisma migrate deploy && node build/index.js
